// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/93bae1bb4c887c1375a4c1f0c3bb849ff06b8ac6/moment/moment.d.ts
declare var moment: moment.MomentStatic;
